### ISSUE TITLE
Remove secrets from workflows who run on Pull Requests

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3288] opened 2024-07-18 13:03 UTC
Having secrets in these workflows would prevent us from running workflows on outside contributions and make it more difficult to check these PRs.

**Comment by alionazherdetska** [comment] 2024-12-11 13:24
Duplicate of [#3532](https://github.com/swisspost/design-system/issues/3532)

**Closed by alionazherdetska** 2024-12-11 13:24 UTC
Labels: 🛠️ workflows
