### ISSUE TITLE
Inability to Create Waybill from Public FBO Page with Unresponsive Application

### ISSUE THREAD

**Issue by Postpost2024** [swisspost/design-system#2789] opened 2024-03-13 23:59 UTC
Inability to Create Waybill from Public Page with Unresponsive Application

 

Reproduce Steps:

Open the public page.
Wait for a few minutes without any activity.
Attempt to create a waybill from the public page.
Notice that the application does not allow data entry for creating the waybill.
Even after refreshing the page, attempt to insert data, but the application remains unresponsive.
Observe the page continuously rotating without any response.
Expected Result:

Users should be able to create a waybill from the public page without encountering unresponsiveness or difficulties in data entry.
Actual Result:

Upon trying to create a waybill, the application becomes unresponsive, preventing users from entering any data. Refreshing the page also does not resolve the issue, and the page continues to rotate without any response.
Link:

https://postchag-my.sharepoint.com/personal/nurzaman_sarkar_post_ch/Documents/Aufnahmen/TEST-20240225_094231-Besprechungsaufzeichnung.mp4?web=1&referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view

 

 

LINK:

https://appstest.post.ch/fb/public/recording/7de27132-773e-4c24-ac8d-8f3750ebacd1/shipping?state=new&status=401&statusText=Unauthorized

**Comment by gfellerph** [comment] 2024-04-12 12:04
@Postpost2024, closing because we're not able to reproduce the issue for further investigation.

**Closed by gfellerph** 2024-04-12 12:04 UTC
Labels: reproduction needed
