### ISSUE TITLE
Add documentation page for scss :export

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#905] opened 2022-12-23 09:58 UTC
Maybe this could be useful for our developers as well ;)
For more informations, see: [#901](https://github.com/swisspost/design-system/pull/901/files/ec3bc686ab1c93d2d2d191348a775b67966c1228#diff-ee5f1b024a1464cd089fbb5b22275b6b486348adcc76e68502ad7ffd11e9aaaa)

**Comment by gfellerph** [comment] 2023-02-09 15:12
@oliverschuerch is this a duplicate of #586?

**Comment by gfellerph** [comment] 2023-03-13 08:50
Closing it as duplicate

**Closed by gfellerph** 2023-03-13 08:50 UTC
Labels: storybook
