### ISSUE TITLE
Component: Drawer

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1974] opened 2023-09-19 16:00 UTC
creat a drawer that can be used for different situations. e.g. 

![Image](https://github.com/swisspost/design-system/assets/20660048/6c9b5f38-37e9-4738-95fe-d0221e113f40)

**Comment by gfellerph** [comment] 2024-06-13 07:36
Closing as duplicate of https://github.com/swisspost/design-system/issues/2278

**Closed by gfellerph** 2024-06-13 07:36 UTC
