### ISSUE TITLE
Knowledge sharing: Who do we need to educate on this topic and how do we approach it?

### ISSUE THREAD

**Issue by Vandapanda** [swisspost/design-system#3401] opened 2024-08-14 08:41 UTC
Discussion how we best spread word about token and the new design system. With the implementation of tokens we also need to teach designers and devs the best way to work with the system. Further it would be good if I tought someone how I handle tokens right now just in case I run into an accident or something.

**Comment by gfellerph** [comment] 2024-08-21 12:55
Alessio: knowledge is centralized for token studio, we need to distribute knowledge about figma building (autolayout) and token studio 
Rouven: There are two topics, we could use experience hub. How much do UX need to know? 
Alessio: We have components that change based on canvas, people need to know how they work
Rouven: Canvas should be delivered ready made
Alessio: Even then you can mess it up
Rouven: Create canvas repository
Snadra: Two use cases: 1. working with tokens as an editor, 2. working with tokenized components. Who should be able to maintain token system? What is needed in terms of docs/knowledge?
Rouven: This is the job of the DS team. 
Phil: do we have the neccessary resources?
Rouven: We need to document it
Rouven: Devs should not edit tokens
Oli: I don't feel responsible for that now. Hard to catch up with the current thoughts behind structure
Alessio: Naming is the hardest thing. Devs can get up to speed. Decisions come from Design side, does not need to be implemented from a Designer
Oli: Would feel unsafe to touch existing components
Alizé: Keeping boundaries is ok
Rouven: Agree, it's a designer job (editing)
Oli: Tokens could be described
Alessio: Not gonna do that
Sandra: 3 action items: Create maintenance docs, create docs for code usage, create docs for design usage.
Oli: Alessio and me had a lot of discussions, defining tokens needs to be a collaboration
Sandra: There needs to be a defined leader
Oli: I would like to have a dev and a designer responsible for tokens. Decisions need to be taken by Design and Development
Rouven: Consultants 
Philipp: BA, RE, Devs?
Oli: nobody outside the team because nobody uses them right now. Can still educate others later.

Actions: Document from 3 points of view. Responsible: Alessio (deadline: December)

**Comment by gfellerph** [comment] 2024-08-22 09:24
Closing in favor of #3448, other documentations (for devs in storybook, for UX Designers in Figma and on the Experience Hub) will follow.

**Closed by gfellerph** 2024-08-22 09:24 UTC
Labels: 🔮 tokens
