### ISSUE TITLE
Update the style imports

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#4129] opened 2024-12-03 08:12 UTC
The style import component is outdated, instead of this: 
```scss
@use '@swisspost/design-system-styles/index.scss';
```
We should show this: 
```scss
@use '@swisspost/design-system-styles/[theme]-[channel].scss';
```
where `theme` and `channel` are automatically set using the currently selected theme and channel (stored in the local storage).

**Comment by gfellerph** [comment] 2024-12-04 08:48
Closing as duplicate of https://github.com/swisspost/design-system/issues/4026

**Closed by gfellerph** 2024-12-04 08:48 UTC
Labels: 📦 documentation
