### ISSUE TITLE
KLP notification widget shown wrong for B2B account

### ISSUE THREAD

**Issue by m-dionisio** [swisspost/design-system#1391] opened 2023-05-08 12:46 UTC
Hello,
when landing on https://int.post.ch/en/customer-center/customer-center with a B2B account, the initials in the notifications widget are not centered correctly. See attachment.
![widget](https://user-images.githubusercontent.com/132910776/236827794-c8586561-f893-4537-85aa-409508ff8edd.jpg)

**Comment by gfellerph** [comment] 2023-06-07 11:24
Closing because issue can't be reproduced any more.

**Closed by gfellerph** 2023-06-07 11:24 UTC
Labels: bug, internet-header
