### ISSUE TITLE
Update disabled form fields

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3236] opened 2024-07-10 11:24 UTC
Disabled input value should be cross out (or the labels when input is empty): 
https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=7775-33876&m=dev

However, disable select value is not crossed out: 
https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=7802-33963&m=dev

Decide on one or the other and implement this choice in the styles.

**Comment by gfellerph** [comment] 2024-07-10 11:46
Asked @rouvenpost about that https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY?node-id=3805-22655&m=dev#869237465

**Comment by gfellerph** [comment] 2024-07-15 09:42
Closing as duplicate of #3216

**Closed by gfellerph** 2024-07-15 09:42 UTC
Labels: 📦 styles
