### ISSUE TITLE
Add role attributes to the internet-header search elements

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#1363] opened 2023-04-24 09:57 UTC
To better identify the search some role attributes can be added.
Add the attribute `role=search` to this element `<div class="search">` and the attribute `role="searchbox"` to this element `<input type="text" id="searchBox" class="form-control form-control-lg" placeholder="Sen..." autocomplete="off">`

**Comment by imagoiq** [comment] 2023-10-04 14:08
Duplicate of https://github.com/swisspost/design-system/issues/1343

**Closed** 2023-10-04 14:08 UTC
Labels: internet-header
