### ISSUE TITLE
Demo: app is not showing

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1463] opened 2023-06-05 15:04 UTC
This is probably due to this issue with NgbDropdown:

![Image](https://github.com/swisspost/design-system/assets/33580481/0eb1f4a1-1091-4279-b32a-4941033ac800)

**Comment by gfellerph** [comment] 2023-06-05 19:35
I think this is a duplicate of #1450, but more info or a resolution would be nice.

**Closed** 2023-06-06 06:59 UTC
Labels: bug, demo
