### ISSUE TITLE
Component: Button Group | Positive

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1977] opened 2023-09-20 06:28 UTC
**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=70%3A407&mode=design&t=ZSoe0MTs3zuKmoiG-1

old
https://www.figma.com/file/KDAqx5qYIhMt5YnB7HJVSE/post_library_atoms?type=design&node-id=0%3A2&mode=design&t=h7jkHjB3i4bxOhVk-1
https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A734&mode=design&t=8fIo91pngO4uaDF5-1

**Dev**
https://next.design-system.post.ch/?path=/docs/components-button-group--docs

**Comment by rouvenpost** [comment] 2024-01-12 12:56
Ready for review

**Comment by Cian77** [comment] 2024-01-22 09:48
@rouvenpost: Made the review, good to go from my side.

**Comment by gfellerph** [comment] 2024-01-24 15:46
Needs additional considerations for mobile (discussed with @Cian77 already a bit):
- What happens with more than 3 buttons on 320px?
  - Switching to a vertical stack would be a possibility
  - Truncating text is not accessible
- What happens with just two buttons in a 1920px fullscreen layout?
  - Could define a max width for a button

Assigning back to @rouvenpost.

**Comment by rouvenpost** [comment] 2024-05-22 05:34
Ready for review

**Comment by gfellerph** [comment] 2024-07-15 07:45
Closing as duplicate of #2593

**Closed by gfellerph** 2024-07-15 07:45 UTC
Labels: 💚 APPROVED, 🦌 fair game
